# **Problem - 1: Array Creation:**
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [3]:
import numpy as np

# 1. Initialize an empty array with size 2X2.
empty_array = np.empty((2, 2))
print("1. Empty Array (2x2):\n", empty_array)

# 2. Initialize an all one array with size 4X2.
ones_array = np.ones((4, 2))
print("\n2. All Ones Array (4x2):\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value.
fill_value_array = np.full((3, 3), 7)  # 3x3 array filled with 7
print("\n3. Filled Array (3x3 with 7):\n", fill_value_array)

# 4. Return a new array of zeros with same shape and type as a given array.
sample_array = np.array([[1, 2], [3, 4]])
zeros_like_array = np.zeros_like(sample_array)
print("\n4. Zeros Like Array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array.
ones_like_array = np.ones_like(sample_array)
print("\n5. Ones Like Array:\n", ones_like_array)

# 6. Convert list to numpy array.
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted Numpy Array:\n", numpy_array)


1. Empty Array (2x2):
 [[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]

2. All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Filled Array (3x3 with 7):
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros Like Array:
 [[0 0]
 [0 0]]

5. Ones Like Array:
 [[1 1]
 [1 1]]

6. Converted Numpy Array:
 [1 2 3 4]


# **Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:**
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [4]:
# 1. Create an array with values ranging from 10 to 49.
range_array = np.arange(10, 50)
print("\n1. Array with values 10 to 49:\n", range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8.
reshaped_array = np.arange(9).reshape(3, 3)
print("\n2. 3x3 Matrix:\n", reshaped_array)

# 3. Create a 3x3 identity matrix.
identity_matrix = np.eye(3)
print("\n3. Identity Matrix (3x3):\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean.
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random Array Mean:\n", mean_value)

# 5. Create a 10x10 array with random values and find min and max values.
large_random_array = np.random.random((10, 10))
min_value = large_random_array.min()
max_value = large_random_array.max()
print("\n5. Min and Max of 10x10 Random Array:\nMin:", min_value, "Max:", max_value)

# 6. Create a zero array of size 10 and replace 5th element with 1.
zero_array = np.zeros(10)
zero_array[4] = 1
print("\n6. Zero Array with 5th Element as 1:\n", zero_array)

# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0].
arr = [1, 2, 0, 0, 4, 0]
reversed_array = arr[::-1]
print("\n7. Reversed Array:\n", reversed_array)

# 8. Create a 2D array with 1 on border and 0 inside.
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D Array with 1 Border and 0 Inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern.
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1  # 1 on odd rows, even columns
checkerboard[::2, 1::2] = 1  # 1 on even rows, odd columns
print("\n9. Checkerboard Pattern (8x8):\n", checkerboard)



1. Array with values 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. Identity Matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random Array Mean:
 0.527640345176376

5. Min and Max of 10x10 Random Array:
Min: 0.016162743839381655 Max: 0.9984670236497122

6. Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed Array:
 [0, 4, 0, 0, 2, 1]

8. 2D Array with 1 Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard Pattern (8x8):
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# **Problem - 3: Array Operations:**
For the following arrays:
x = np.array([[1,2],[3,5]])

y = np.array([[5,6],[7,8]])

v = np.array([9,10])

 w = np.array([11,12])

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [5]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#1. Add the two arrays
sum_array = x + y
print("1. Addition of x and y:\n", sum_array)

#2. Subtract the two arrays
diff_array = x - y
print("\n2. Subtraction of x and y:\n", diff_array)

#3. Multiply the array with any integer (e.g., 3)
scaled_array = x * 3
print("\n3. Multiplication of x with 3:\n", scaled_array)

#4. Find the square of each element
squared_array = np.square(x)
print("\n4. Square of each element in x:\n", squared_array)

#5. Dot product:
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)

print("\n5. Dot product:\n v·w =", dot_vw, "\n x·v:\n", dot_xv, "\n x·y:\n", dot_xy)

#6. Concatenate x and y along rows and v and w along columns
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))

print("\n6. Concatenation along rows:\n", concat_xy)
print("\nConcatenation along columns:\n", concat_vw)

#7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    print("\n7. Error when concatenating x and v:\n", e)



1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5. Dot product:
 v·w = 219 
 x·v:
 [29 77] 
 x·y:
 [[19 22]
 [50 58]]

6. Concatenation along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation along columns:
 [[ 9 10]
 [11 12]]

7. Error when concatenating x and v:
 all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


# **Problem - 4: Matrix Operations:**
• For the following arrays:

A = np.array([[3,4],[7,8]])

B = np.array([[5,3],[2,1]])

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [6]:
#Given
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

#1. Prove 𝐴⋅𝐴−1=𝐼A⋅A −1 = I
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("1. Proving A·A⁻¹ = I:\n", identity_matrix)

#2. Prove 𝐴𝐵≠𝐵𝐴
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("Are AB and BA equal? ", np.array_equal(AB, BA))

#3. Prove (𝐴𝐵)𝑇=𝐵𝑇⋅𝐴𝑇(AB)T =BT ⋅ AT
AB_transpose = np.transpose(np.dot(A, B))
BT_AT = np.dot(B.T, A.T)
print("\n3. Proving (AB)^T = B^T·A^T:\n", AB_transpose)
print("\nB^T·A^T:\n", BT_AT)

#2x−3y+z=−1
#x−y+2z=−3
#3x+y−z=9
#Represent in matrix form
# AX=B:
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

#Solve using np.linalg.inv:
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
print("\nSolution using inverse method:\n", X)

#Solve using NumPy:
X_direct = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve:\n", X_direct)



1. Proving A·A⁻¹ = I:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Are AB and BA equal?  False

3. Proving (AB)^T = B^T·A^T:
 [[23 51]
 [13 29]]

B^T·A^T:
 [[23 51]
 [13 29]]

Solution using inverse method:
 [ 2.  1. -2.]

Solution using np.linalg.solve:
 [ 2.  1. -2.]


# Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [7]:
import numpy as np
import time

# 1. Element-wise Addition
list_size = 1_000_000
python_list1 = [i for i in range(list_size)]
python_list2 = [i for i in range(list_size)]
numpy_array1 = np.arange(list_size)
numpy_array2 = np.arange(list_size)

# Using Python Lists
start_time = time.time()
python_result = [python_list1[i] + python_list2[i] for i in range(list_size)]
end_time = time.time()
print("1. Element-wise Addition (Python Lists):", end_time - start_time, "seconds")

# Using NumPy Arrays
start_time = time.time()
numpy_result = numpy_array1 + numpy_array2
end_time = time.time()
print("1. Element-wise Addition (NumPy):", end_time - start_time, "seconds")

# 2. Element-wise Multiplication
# Using Python Lists
start_time = time.time()
python_result = [python_list1[i] * python_list2[i] for i in range(list_size)]
end_time = time.time()
print("\n2. Element-wise Multiplication (Python Lists):", end_time - start_time, "seconds")

# Using NumPy Arrays
start_time = time.time()
numpy_result = numpy_array1 * numpy_array2
end_time = time.time()
print("2. Element-wise Multiplication (NumPy):", end_time - start_time, "seconds")

# 3. Dot Product
# Using Python Lists
start_time = time.time()
dot_product_python = sum(python_list1[i] * python_list2[i] for i in range(list_size))
end_time = time.time()
print("\n3. Dot Product (Python Lists):", end_time - start_time, "seconds")

# Using NumPy Arrays
start_time = time.time()
dot_product_numpy = np.dot(numpy_array1, numpy_array2)
end_time = time.time()
print("3. Dot Product (NumPy):", end_time - start_time, "seconds")

# 4. Matrix Multiplication
matrix_size = 1000
python_matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
python_matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
numpy_matrix1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
numpy_matrix2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

# Using Python Lists
start_time = time.time()
result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*python_matrix2)] for row in python_matrix1]
end_time = time.time()
print("\n4. Matrix Multiplication (Python Lists):", end_time - start_time, "seconds")

# Using NumPy Arrays
start_time = time.time()
numpy_result = np.dot(numpy_matrix1, numpy_matrix2)
end_time = time.time()
print("4. Matrix Multiplication (NumPy):", end_time - start_time, "seconds")


1. Element-wise Addition (Python Lists): 0.27733874320983887 seconds
1. Element-wise Addition (NumPy): 0.005076885223388672 seconds

2. Element-wise Multiplication (Python Lists): 0.3952453136444092 seconds
2. Element-wise Multiplication (NumPy): 0.02890610694885254 seconds

3. Dot Product (Python Lists): 0.6143052577972412 seconds
3. Dot Product (NumPy): 0.0022268295288085938 seconds

4. Matrix Multiplication (Python Lists): 201.66209936141968 seconds
4. Matrix Multiplication (NumPy): 1.1808314323425293 seconds
